### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir '/opt/botkit-starter-ryver/components/express_middleware'

### ISSUE THREAD

**Issue by Gelob** [RyverApp/botkit-starter-ryver#1]
I git cloned this repo into /opt/ on a fresh CentOS 7.5 system. npm install completed fine. After that when trying to run `node .` in the botkit-starter-ryver directory I get the following error. It would be helpful if the instructions included how to start the bot for someone not familiar with node. I made the directory manually and it appeared to work fine. `mkdir components/express_middleware`

```
[root@NetOps-VM-2 botkit-starter-ryver]# npm install
botkit-starter-ryver@1.0.0 /opt/botkit-starter-ryver
├─┬ body-parser@1.18.3
│ ├── bytes@3.0.0
│ ├── content-type@1.0.4
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├── depd@1.1.2
│ ├─┬ http-errors@1.6.3
│ │ ├── inherits@2.0.3
│ │ └── statuses@1.5.0
│ ├─┬ iconv-lite@0.4.23
│ │ └── safer-buffer@2.1.2
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── qs@6.5.2
│ ├─┬ raw-body@2.3.3
│ │ └── unpipe@1.0.0
│ └─┬ type-is@1.6.16
│   └── media-typer@0.3.0
├─┬ botkit@0.6.21
│ ├─┬ async@2.6.1
│ │ └── lodash@4.17.11
│ ├─┬ back@1.0.2
│ │ └── xtend@4.0.1
│ ├─┬ botbuilder@3.16.0
│ │ ├── @types/async@2.4.0
│ │ ├─┬ @types/express@4.16.1
│ │ │ ├─┬ @types/body-parser@1.17.0
│ │ │ │ └── @types/connect@3.4.32
│ │ │ ├─┬ @types/express-serve-static-core@4.16.1
│ │ │ │ └── @types/range-parser@1.2.3
│ │ │ └─┬ @types/serve-static@1.13.2
│ │ │   └── @types/mime@2.0.0
│ │ ├── @types/form-data@2.2.1
│ │ ├── @types/jsonwebtoken@7.2.8
│ │ ├── @types/node@9.6.41
│ │ ├─┬ @types/request@2.48.1
│ │ │ ├── @types/caseless@0.12.1
│ │ │ └── @types/tough-cookie@2.3.5
│ │ ├── @types/sprintf-js@1.1.1
│ │ ├── @types/url-join@0.8.3
│ │ ├── async@1.5.2
│ │ ├── base64url@3.0.1
│ │ ├─┬ chrono-node@1.3.5
│ │ │ └── moment@2.24.0
│ │ ├─┬ jsonwebtoken@8.4.0
│ │ │ ├─┬ jws@3.2.0
│ │ │ │ └─┬ jwa@1.2.0
│ │ │ │   ├── buffer-equal-constant-time@1.0.1
│ │ │ │   └── ecdsa-sig-formatter@1.0.10
│ │ │ ├── lodash.includes@4.3.0
│ │ │ ├── lodash.isboolean@3.0.3
│ │ │ ├── lodash.isinteger@4.0.4
│ │ │ ├── lodash.isnumber@3.0.3
│ │ │ ├── lodash.isplainobject@4.0.6
│ │ │ ├── lodash.isstring@4.0.1
│ │ │ ├── lodash.once@4.1.1
│ │ │ └── ms@2.1.1
│ │ ├─┬ promise@7.3.1
│ │ │ └── asap@2.0.6
│ │ ├── rsa-pem-from-mod-exp@0.8.4
│ │ ├── sprintf-js@1.1.2
│ │ └── url-join@1.1.0
│ ├─┬ botkit-studio-sdk@1.0.9
│ │ └── promise@8.0.2
│ ├─┬ chalk@2.4.2
│ │ ├─┬ ansi-styles@3.2.1
│ │ │ └─┬ color-convert@1.9.3
│ │ │   └── color-name@1.1.3
│ │ ├── escape-string-regexp@1.0.5
│ │ └─┬ supports-color@5.5.0
│ │   └── has-flag@3.0.0
│ ├─┬ ciscospark@1.32.23
│ │ ├─┬ @ciscospark/internal-plugin-wdm@1.32.23
│ │ │ ├─┬ @ciscospark/common@1.32.23
│ │ │ │ ├─┬ backoff@2.5.0
│ │ │ │ │ └── precond@0.2.3
│ │ │ │ ├── core-decorators@0.20.0
│ │ │ │ └── urlsafe-base64@1.0.0
│ │ │ ├── @ciscospark/common-timers@1.32.23
│ │ │ ├─┬ @ciscospark/http-core@1.32.23
│ │ │ │ ├── file-type@3.9.0
│ │ │ │ ├─┬ global@4.3.2
│ │ │ │ │ ├─┬ min-document@2.19.0
│ │ │ │ │ │ └── dom-walk@0.1.1
│ │ │ │ │ └── process@0.5.2
│ │ │ │ ├── is-function@1.0.1
│ │ │ │ └─┬ parse-headers@2.0.1
│ │ │ │   ├─┬ for-each@0.3.3
│ │ │ │   │ └── is-callable@1.1.4
│ │ │ │   └── trim@0.0.1
│ │ │ ├─┬ ampersand-collection@2.0.2
│ │ │ │ ├── ampersand-class-extend@2.0.0
│ │ │ │ └─┬ ampersand-version@1.0.2
│ │ │ │   ├── find-root@0.1.2
│ │ │ │   └─┬ through2@0.6.5
│ │ │ │     └─┬ readable-stream@1.0.34
│ │ │ │       ├── isarray@0.0.1
│ │ │ │       └── string_decoder@0.10.31
│ │ │ ├─┬ ampersand-state@5.0.3
│ │ │ │ ├── array-next@0.0.1
│ │ │ │ └── key-tree-store@1.3.0
│ │ │ └─┬ babel-runtime@6.26.0
│ │ │   └── regenerator-runtime@0.11.1
│ │ ├─┬ @ciscospark/plugin-authorization@1.32.23
│ │ │ ├── @ciscospark/plugin-authorization-browser@1.32.23
│ │ │ └── @ciscospark/plugin-authorization-node@1.32.23
│ │ ├── @ciscospark/plugin-logger@1.32.23
│ │ ├── @ciscospark/plugin-memberships@1.32.23
│ │ ├── @ciscospark/plugin-messages@1.32.23
│ │ ├── @ciscospark/plugin-people@1.32.23
│ │ ├─┬ @ciscospark/plugin-phone@1.32.23
│ │ │ ├─┬ @ciscospark/internal-plugin-locus@1.32.23
│ │ │ │ └─┬ @ciscospark/internal-plugin-mercury@1.32.23
│ │ │ │   ├── @ciscospark/internal-plugin-feature@1.32.23
│ │ │ │   └── ws@4.1.0
│ │ │ ├── @ciscospark/internal-plugin-metrics@1.32.23
│ │ │ ├─┬ @ciscospark/media-engine-webrtc@1.32.23
│ │ │ │ ├── @ciscospark/common-evented@1.32.23
│ │ │ │ ├── bowser@1.9.4
│ │ │ │ └─┬ webrtc-adapter@6.4.8
│ │ │ │   ├── rtcpeerconnection-shim@1.2.15
│ │ │ │   └── sdp@2.9.0
│ │ │ ├── ampersand-collection-lodash-mixin@4.0.0
│ │ │ ├── detectrtc@1.3.9
│ │ │ ├─┬ lodash-decorators@4.5.0
│ │ │ │ └── tslib@1.9.3
│ │ │ └── sdp-transform@2.7.0
│ │ ├── @ciscospark/plugin-rooms@1.32.23
│ │ ├── @ciscospark/plugin-team-memberships@1.32.23
│ │ ├── @ciscospark/plugin-teams@1.32.23
│ │ ├── @ciscospark/plugin-webhooks@1.32.23
│ │ ├─┬ @ciscospark/spark-core@1.32.23
│ │ │ └── ampersand-events@2.0.2
│ │ ├── @ciscospark/storage-adapter-local-storage@1.32.23
│ │ ├─┬ babel-polyfill@6.26.0
│ │ │ ├── core-js@2.6.3
│ │ │ └── regenerator-runtime@0.10.5
│ │ └─┬ envify@4.1.0
│ │   ├── esprima@4.0.1
│ │   └── through@2.3.8
│ ├── clone@2.1.2
│ ├─┬ command-line-args@5.0.2
│ │ ├── argv-tools@0.1.1
│ │ ├── array-back@2.0.0
│ │ ├─┬ find-replace@2.0.1
│ │ │ └── test-value@3.0.0
│ │ ├── lodash.camelcase@4.3.0
│ │ └── typical@2.6.1
│ ├─┬ command-line-usage@5.0.5
│ │ └─┬ table-layout@0.4.4
│ │   ├── deep-extend@0.6.0
│ │   ├── lodash.padend@4.6.1
│ │   └─┬ wordwrapjs@3.0.0
│ │     └── reduce-flatten@1.0.1
│ ├── email-addresses@3.0.3
│ ├─┬ googleapis@34.0.0
│ │ ├─┬ google-auth-library@2.0.2
│ │ │ ├── axios@0.18.0
│ │ │ ├─┬ gcp-metadata@0.7.0
│ │ │ │ └── retry-axios@0.3.2
│ │ │ ├─┬ gtoken@2.3.2
│ │ │ │ ├─┬ gaxios@1.2.6
│ │ │ │ │ └── node-fetch@2.3.0
│ │ │ │ ├─┬ google-p12-pem@1.0.3
│ │ │ │ │ └── node-forge@0.7.6
│ │ │ │ ├── mime@2.4.0
│ │ │ │ └── pify@4.0.1
│ │ │ ├─┬ lru-cache@5.1.1
│ │ │ │ └── yallist@3.0.3
│ │ │ └── semver@5.6.0
│ │ └─┬ googleapis-common@0.3.0
│ │   ├── pify@3.0.0
│ │   └── url-template@2.0.8
│ ├─┬ https-proxy-agent@2.2.1
│ │ ├─┬ agent-base@4.2.1
│ │ │ └─┬ es6-promisify@5.0.0
│ │ │   └── es6-promise@4.2.5
│ │ └─┬ debug@3.2.6
│ │   └── ms@2.1.1
│ ├─┬ jfs@0.3.0
│ │ ├── async@2.5.0
│ │ └─┬ mkdirp@0.5.1
│ │   └── minimist@0.0.8
│ ├─┬ localtunnel@1.9.1
│ │ ├─┬ axios@0.17.1
│ │ │ └─┬ follow-redirects@1.6.1
│ │ │   └── debug@3.1.0
│ │ ├── debug@2.6.9
│ │ ├── openurl@1.1.1
│ │ └─┬ yargs@6.6.0
│ │   ├── camelcase@3.0.0
│ │   ├─┬ cliui@3.2.0
│ │   │ ├─┬ strip-ansi@3.0.1
│ │   │ │ └── ansi-regex@2.1.1
│ │   │ └── wrap-ansi@2.1.0
│ │   ├── decamelize@1.2.0
│ │   ├── get-caller-file@1.0.3
│ │   ├─┬ os-locale@1.4.0
│ │   │ └─┬ lcid@1.0.0
│ │   │   └── invert-kv@1.0.0
│ │   ├─┬ read-pkg-up@1.0.1
│ │   │ ├─┬ find-up@1.1.2
│ │   │ │ ├── path-exists@2.1.0
│ │   │ │ └─┬ pinkie-promise@2.0.1
│ │   │ │   └── pinkie@2.0.4
│ │   │ └─┬ read-pkg@1.1.0
│ │   │   ├─┬ load-json-file@1.1.0
│ │   │   │ ├── graceful-fs@4.1.15
│ │   │   │ ├─┬ parse-json@2.2.0
│ │   │   │ │ └─┬ error-ex@1.3.2
│ │   │   │ │   └── is-arrayish@0.2.1
│ │   │   │ ├── pify@2.3.0
│ │   │   │ └─┬ strip-bom@2.0.0
│ │   │   │   └── is-utf8@0.2.1
│ │   │   ├─┬ normalize-package-data@2.4.0
│ │   │   │ ├── hosted-git-info@2.7.1
│ │   │   │ ├─┬ is-builtin-module@1.0.0
│ │   │   │ │ └── builtin-modules@1.1.1
│ │   │   │ └─┬ validate-npm-package-license@3.0.4
│ │   │   │   ├─┬ spdx-correct@3.1.0
│ │   │   │   │ └── spdx-license-ids@3.0.3
│ │   │   │   └─┬ spdx-expression-parse@3.0.0
│ │   │   │     └── spdx-exceptions@2.2.0
│ │   │   └─┬ path-type@1.1.0
│ │   │     └── pify@2.3.0
│ │   ├── require-directory@2.1.1
│ │   ├── require-main-filename@1.0.1
│ │   ├── set-blocking@2.0.0
│ │   ├─┬ string-width@1.0.2
│ │   │ ├── code-point-at@1.1.0
│ │   │ └─┬ is-fullwidth-code-point@1.0.0
│ │   │   └── number-is-nan@1.0.1
│ │   ├── which-module@1.0.0
│ │   ├── y18n@3.2.1
│ │   └── yargs-parser@4.2.1
│ ├─┬ md5@2.2.1
│ │ ├── charenc@0.0.2
│ │ ├── crypt@0.0.2
│ │ └── is-buffer@1.1.6
│ ├── mustache@3.0.1
│ ├─┬ prompts@1.2.1
│ │ ├── kleur@3.0.1
│ │ └── sisteransi@1.0.0
│ ├─┬ requestretry@3.1.0
│ │ └── when@3.7.8
│ ├─┬ simple-xmpp@1.3.1
│ │ ├─┬ node-xmpp-client@3.2.0
│ │ │ ├── browser-request@0.3.3
│ │ │ ├── debug@2.6.9
│ │ │ ├─┬ md5.js@1.3.5
│ │ │ │ └── hash-base@3.0.4
│ │ │ ├── minimist@1.2.0
│ │ │ ├─┬ node-xmpp-core@5.0.9
│ │ │ │ ├── @xmpp/jid@0.0.2
│ │ │ │ ├─┬ @xmpp/streamparser@0.0.6
│ │ │ │ │ └── ltx@2.8.1
│ │ │ │ ├── @xmpp/xml@0.1.3
│ │ │ │ ├── debug@2.6.9
│ │ │ │ ├── lodash.assign@4.2.0
│ │ │ │ ├── node-xmpp-tls-connect@1.0.1
│ │ │ │ └─┬ reconnect-core@0.0.1
│ │ │ │   └── backoff@2.3.0
│ │ │ └─┬ ws@1.1.5
│ │ │   ├── options@0.0.6
│ │ │   └── ultron@1.0.2
│ │ └── qbox@0.1.7
│ ├─┬ twilio@3.27.1
│ │ ├── deprecate@1.0.0
│ │ ├── moment@2.19.3
│ │ ├─┬ q@2.0.3
│ │ │ ├── pop-iterate@1.0.1
│ │ │ └── weak-map@1.0.5
│ │ ├── rootpath@0.1.2
│ │ ├── scmp@2.0.0
│ │ └── xmlbuilder@9.0.1
│ ├─┬ ware@1.3.0
│ │ └─┬ wrap-fn@0.1.5
│ │   └── co@3.1.0
│ └─┬ ws@6.1.3
│   └── async-limiter@1.0.0
├── botkit-ryver-connector@1.0.3
├─┬ debug@4.1.1
│ └── ms@2.1.1
├─┬ express@4.16.4
│ ├─┬ accepts@1.3.5
│ │ └── negotiator@0.6.1
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.2
│ ├── cookie@0.3.1
│ ├── cookie-signature@1.0.6
│ ├── debug@2.6.9
│ ├── encodeurl@1.0.2
│ ├── escape-html@1.0.3
│ ├── etag@1.8.1
│ ├─┬ finalhandler@1.1.1
│ │ ├── debug@2.6.9
│ │ └── statuses@1.4.0
│ ├── fresh@0.5.2
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├── parseurl@1.3.2
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@2.0.4
│ │ ├── forwarded@0.1.2
│ │ └── ipaddr.js@1.8.0
│ ├── range-parser@1.2.0
│ ├── safe-buffer@5.1.2
│ ├─┬ send@0.16.2
│ │ ├── debug@2.6.9
│ │ ├── destroy@1.0.4
│ │ ├── mime@1.4.1
│ │ └── statuses@1.4.0
│ ├── serve-static@1.13.2
│ ├── setprototypeof@1.1.0
│ ├── statuses@1.4.0
│ ├── utils-merge@1.0.1
│ └── vary@1.1.2
├── node-env-file@0.1.8
└─┬ request@2.88.0
  ├── aws-sign2@0.7.0
  ├── aws4@1.8.0
  ├── caseless@0.12.0
  ├─┬ combined-stream@1.0.7
  │ └── delayed-stream@1.0.0
  ├── extend@3.0.2
  ├── forever-agent@0.6.1
  ├─┬ form-data@2.3.3
  │ └── asynckit@0.4.0
  ├─┬ har-validator@5.1.3
  │ ├─┬ ajv@6.7.0
  │ │ ├── fast-deep-equal@2.0.1
  │ │ ├── fast-json-stable-stringify@2.0.0
  │ │ ├── json-schema-traverse@0.4.1
  │ │ └─┬ uri-js@4.2.2
  │ │   └── punycode@2.1.1
  │ └── har-schema@2.0.0
  ├─┬ http-signature@1.2.0
  │ ├── assert-plus@1.0.0
  │ ├─┬ jsprim@1.4.1
  │ │ ├── extsprintf@1.3.0
  │ │ ├── json-schema@0.2.3
  │ │ └─┬ verror@1.10.0
  │ │   └── core-util-is@1.0.2
  │ └─┬ sshpk@1.16.1
  │   ├── asn1@0.2.4
  │   ├── bcrypt-pbkdf@1.0.2
  │   ├── dashdash@1.14.1
  │   ├── ecc-jsbn@0.1.2
  │   ├── getpass@0.1.7
  │   ├── jsbn@0.1.1
  │   └── tweetnacl@0.14.5
  ├── is-typedarray@1.0.0
  ├── isstream@0.1.2
  ├── json-stringify-safe@5.0.1
  ├─┬ mime-types@2.1.21
  │ └── mime-db@1.37.0
  ├── oauth-sign@0.9.0
  ├── performance-now@2.1.0
  ├─┬ tough-cookie@2.4.3
  │ ├── psl@1.1.31
  │ └── punycode@1.4.1
  ├── tunnel-agent@0.6.0
  └── uuid@3.3.2

```

```
[root@NetOps-VM-2 botkit-starter-ryver]# node .
~~~~~~~~~~
NOTE: Webhook signature validation has not been enabled
To enable, pass in a webhook_secret parameter as specified when configuring the webhook in Ryver
Initializing Botkit v0.6.21
info: ** No persistent storage method specified! Data may be lost when process shuts down.
fs.js:961
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/opt/botkit-starter-ryver/components/express_middleware'
    at Error (native)
    at Object.fs.readdirSync (fs.js:961:18)
    at module.exports (/opt/botkit-starter-ryver/components/express_webserver.js:13:19)
    at Object.<anonymous> (/opt/botkit-starter-ryver/bot.js:37:56)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
```

**Comment by LukeBaulch** [comment]
Apologies for this @Gelob. After the announcement of botkit-studio's discontinuation I had removed the associated middleware file leaving this `express_middleware` folder empty, therefore being excluded from the git repository.  As we no longer need to load middleware I've now removed the code that required this folder. Thanks for letting us know.
